administratorservice/urls.py
from django.urls import path

from .views import *

app_name = 'administrator_service'
urlpatterns = [
    path('dashboard/', dashboard, name='dashboard'),
    path('otp/', otp_list, name='otp_list'),
    path('roles/', roles_list, name='roles_list'),
    path('roles/create/', create_roles, name='create_roles'),
    # path('roles/modify/<int:pk>/', update_roles, name='update_roles'),
    # path('roles/modify/<int:pk>/', delete_roles, name='delete_roles'),

    path('asset-type/', asset_type_list, name='asset_type_list'),
    path('asset-type/create/', create_asset_type, name='create_asset_type'),




    path('breed/', breed_list, name='breed_list'),
    path('breed/create/', create_breed, name='create_breed'),

    path('color/', color_list, name='color_list'),
    path('color/create/', create_color, name='create_color'),

    path('vaccination-status/', vaccination_status_list, name='vaccination_status_list'),
    path('vaccination-status/create/', create_vaccination_status, name='create_vaccination_status'),

    path('deworming-status/', deworming_status_list, name='deworming_status_list'),
    path('deworming-status/create/', create_deworming_status, name='create_deworming_status'),

    path('user-module-access/', user_module_access_list, name='user_module_access_list'),
    path('user-module-access/create/', create_user_module_access, name='create_user_module_access'),


    path('users/', users_list, name='users_list'),
    path('users/create/', create_user, name='create_users'),
    path('users/create-insurecow-agent/', create_insurecow_agent, name='create_insurecow_users'),
    # path('users/modify/<int:pk>/', users_roles, name='update_roles'),
    # path('users/modify/<int:pk>/', users_roles, name='delete_roles'),

]

apiservice/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('auth/public/register/step1/', RegisterStep1.as_view(), name='register-step1'),
    path('auth/public/register/verify-otp/', VerifyOTP.as_view(), name='verify-otp'),
    path('auth/public/register/set-password/', SetPassword.as_view(), name='set-password'),

    path('auth/public/forgot-password/request/', ForgotPasswordRequestView.as_view(), name='forgot-password-request'),
    path('auth/public/forgot-password/verify/', ForgotPasswordVerifyOTPView.as_view(), name='forgot-password-verify'),
    path('auth/public/forgot-password/set/', ForgotPasswordSetView.as_view(), name='forgot-password-set'),


    path('auth/public/login/', Login.as_view(), name='login'),

    path('auth/user/personal-info/', SetPersonalInfo.as_view(), name='personal-info'),
    path('auth/user/financial-info/', SetFinancialInfo.as_view(), name='financial-info'),
    path('auth/user/nominee-info/', SetNomineeInfo.as_view(), name='nominee-info'),
    path('auth/user/organization-info/', SetOrganizationInfo.as_view(), name='organization-info'),

    path('auth/public/token/verify/', VerifyTokenView.as_view(), name='verify-token'),

    path('auth/public/role-list/', RoleListAPIView.as_view(), name='role-list'),
    path('auth/admin/role/', RoleListCreateAPIView.as_view(), name='role-list-create'),
    path('auth/admin/role/<int:pk>/', RoleRetrieveUpdateDestroyAPIView.as_view(), name='role-detail'),
    path('auth/user/sub-users/', SubUsersAPIView.as_view(), name='sub-users'),
    path('auth/user/change-password/', ChangePasswordAPIView.as_view(), name='change-password'),

    path('assets-type/', AssetTypeListAPIView.as_view(), name='asset-type-list'),
    path('breeds/', BreedListAPIView.as_view(), name='breed-list'),
    path('colors/', ColorListAPIView.as_view(), name='color-list'),
    path('vaccination-status/', VaccinationStatusListAPIView.as_view(), name='vaccination-status-list'),
    path('deworming-status/', DewormingStatusListAPIView.as_view(), name='deworming-status-list'),

    path('asset-list/', AssetListAPIView.as_view(), name='asset-list'),
    path('create-asset/', AssetCreateAPIView.as_view(), name='asset-create'),
    path('assets/<int:pk>/', AssetDetailAPIView.as_view(), name='asset-detail'),
    path('get-cow/', get_cow_by_reference, name='get_cow_by_reference'),
    path('insurance-product/', CompanyWiseInsuranceAPIView.as_view(), name='nominee-info'),
    path('insurance-apply/', AssetInsuranceCreateAPIView.as_view(), name='asset-insurance-apply'),
    path('insurance-claim/', InsuranceClaimCreateAPIView.as_view(), name='insurance-claim'),
    path('insurance-list/', InsurancelistAPIView.as_view(), name='insurance-claim'),

    path('payments/create/', PaymentInformationCreateView, name='payment-create'),
    path('payments/<int:pk>/', PaymentInformationDetailView.as_view(), name='payment-detail'),

    path('payments/by-insurance/<str:insurance_id>/', PaymentByInsuranceAPIView.as_view(), name='payments-by-insurance'),

]

enterpriseservice/urls.py
from django.urls import path

from .views import *

app_name = 'enterprise_service'
urlpatterns = [

    path('dashboard/', dashboard, name='dashboard'),
    path('agent-dashboard/', agent_dashboard, name='agent_dashboard'),
    path('users/', users_list, name='users_list'),
    path('users/create-farmer/', create_farmer, name='create_farmer'),
    path('users/create-staff/', create_staff, name='create_staff'),
]

insuranceportal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('administrator/', include('administratorservice.urls')),
    path('insurecow-agent/', include('insurecowagentservice.urls')),
    path('insurance-company/', include('insurancecompanyservice.urls')),
    path('enterprise/', include('enterpriseservice.urls')),
    path('auth/', include('authservice.urls')),
    path('insurance/', include('insuranceservice.urls')),
    path('', include('coreservice.urls')),
    path('api/v1/', include('apiservice.urls')),
    path('api/lms/', include('livestock_management_system.urls')),
    path('api/gls/', include('general_accounting_management_system.urls')),  
    path('api/ims/', include('insurance_management_system.urls')), 
    path('api/fms/', include('farm_management_system.urls')),   
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT})
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/pages/enterprise/user/create_enterprise_agent.html
{% extends '_base.html' %}
{% load static %}

{% block title %}
    Create Enterprise Agent
{% endblock title %}

{% block content %}
    <div class="tp-main-wrapper bg-slate-100 h-screen" x-data="{ sideMenu: false }">
        {% include 'pages/base/sidebar.html' %}

        <div class="tp-main-content lg:ml-[250px] xl:ml-[300px] w-[calc(100% - 300px)]" x-data="{ searchOverlay: false }">

            {% include 'pages/base/header.html' %}

            <div class="body-content px-6 py-8 bg-slate-100">
                <div class="max-w-3xl mx-auto bg-white p-6 rounded-lg shadow-lg">
                    <h1 class="text-3xl font-semibold text-gray-800 mb-6 text-center">Create Enterprise Agent</h1>

                    <form method="POST" enctype="multipart/form-data" class="space-y-6" action="{% url 'enterprise_service:create_staff' %}">
                        {% csrf_token %}

                        <!-- Mobile Number and Password -->
                        <div class="flex flex-col">
                            <label for="mobile_number" class="text-sm font-medium text-gray-700">Mobile Number:</label>
                            <input type="text" id="mobile_number" name="mobile_number" required class="px-4 py-2 mt-2 border rounded-lg focus:ring-2 focus:ring-indigo-500">
                        </div>

                        <div class="flex flex-col">
                            <label for="password" class="text-sm font-medium text-gray-700">Password:</label>
                            <input type="password" id="password" name="password" required class="px-4 py-2 mt-2 border rounded-lg focus:ring-2 focus:ring-indigo-500">
                        </div>

                        <!-- User Personal Info -->
                        <div class="flex flex-col">
                            <label for="first_name" class="text-sm font-medium text-gray-700">First Name:</label>
                            <input type="text" id="first_name" name="first_name" required class="px-4 py-2 mt-2 border rounded-lg focus:ring-2 focus:ring-indigo-500">
                        </div>

                        <div class="flex flex-col">
                            <label for="last_name" class="text-sm font-medium text-gray-700">Last Name:</label>
                            <input type="text" id="last_name" name="last_name" required class="px-4 py-2 mt-2 border rounded-lg focus:ring-2 focus:ring-indigo-500">
                        </div>

                        <div class="flex flex-col">
                            <label for="thana" class="text-sm font-medium text-gray-700">Thana:</label>
                            <input type="text" id="thana" name="thana" required class="px-4 py-2 mt-2 border rounded-lg focus:ring-2 focus:ring-indigo-500">
                        </div>
                        <div class="flex flex-col">
                            <label for="union" class="text-sm font-medium text-gray-700">Union:</label>
                            <input type="text" id="union" name="union" required class="px-4 py-2 mt-2 border rounded-lg focus:ring-2 focus:ring-indigo-500">
                        </div>
                        <div class="flex flex-col">
                            <label for="village" class="text-sm font-medium text-gray-700">Village:</label>
                            <input type="text" id="village" name="village" required class="px-4 py-2 mt-2 border rounded-lg focus:ring-2 focus:ring-indigo-500">
                        </div>
                        <div class="flex flex-col">
                            <label for="zilla" class="text-sm font-medium text-gray-700">Zilla:</label>
                            <input type="text" id="zilla" name="zilla" required class="px-4 py-2 mt-2 border rounded-lg focus:ring-2 focus:ring-indigo-500">
                        </div>

                        <div class="flex flex-col">
                            <label for="nid" class="text-sm font-medium text-gray-700">NID:</label>
                            <input type="text" id="nid" name="nid" class="px-4 py-2 mt-2 border rounded-lg focus:ring-2 focus:ring-indigo-500">
                        </div>

                        <div class="flex flex-col">
                            <label for="date_of_birth" class="text-sm font-medium text-gray-700">Date of Birth:</label>
                            <input type="date" id="date_of_birth" name="date_of_birth" class="px-4 py-2 mt-2 border rounded-lg focus:ring-2 focus:ring-indigo-500">
                        </div>

                        <div class="flex flex-col">
                            <label for="gender" class="text-sm font-medium text-gray-700">Gender:</label>
                            <select id="gender" name="gender" class="px-4 py-2 mt-2 border rounded-lg focus:ring-2 focus:ring-indigo-500">
                                <option value="male">Male</option>
                                <option value="female">Female</option>
                                <option value="other">Other</option>
                            </select>
                        </div>

                        <div class="flex flex-col">
                            <label for="profile_image" class="text-sm font-medium text-gray-700">Profile Image:</label>
                            <input type="file" id="profile_image" name="profile_image" class="px-4 py-2 mt-2 border rounded-lg">
                        </div>

                        <div class="flex flex-col">
                            <label for="nid_front" class="text-sm font-medium text-gray-700">NID Front Image:</label>
                            <input type="file" id="nid_front" name="nid_front" class="px-4 py-2 mt-2 border rounded-lg">
                        </div>

                        <div class="flex flex-col">
                            <label for="nid_back" class="text-sm font-medium text-gray-700">NID Back Image:</label>
                            <input type="file" id="nid_back" name="nid_back" class="px-4 py-2 mt-2 border rounded-lg">
                        </div>
                        <button type="submit" class="w-full py-2 px-4 bg-black text-white rounded-lg hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 mt-4">Create Agent</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/pages/enterprise/user/create_user.html
{% extends '_base.html' %}
{% load static %}

{% block title %}
    Create Farmer
{% endblock title %}

{% block content %}
    <div class="tp-main-wrapper bg-slate-100 h-screen" x-data="{ sideMenu: false }">
        {% include 'pages/base/sidebar.html' %}

        <div class="tp-main-content lg:ml-[250px] xl:ml-[300px] w-[calc(100% - 300px)]" x-data="{ searchOverlay: false }">

            {% include 'pages/base/header.html' %}

            <div class="body-content px-6 py-8 bg-slate-100">
                <div class="max-w-3xl mx-auto bg-white p-6 rounded-lg shadow-lg">
                    <h1 class="text-3xl font-semibold text-gray-800 mb-6 text-center">Create Farmer</h1>

                    <form method="POST" enctype="multipart/form-data" class="space-y-6" action="{% url 'enterprise_service:create_farmer' %}">
                        {% csrf_token %}

                        <!-- Mobile Number and Password -->
                        <div class="flex flex-col">
                            <label for="mobile_number" class="text-sm font-medium text-gray-700">Mobile Number:</label>
                            <input type="text" id="mobile_number" name="mobile_number" required class="px-4 py-2 mt-2 border rounded-lg focus:ring-2 focus:ring-indigo-500">
                        </div>

                        <div class="flex flex-col">
                            <label for="password" class="text-sm font-medium text-gray-700">Password:</label>
                            <input type="password" id="password" name="password" required class="px-4 py-2 mt-2 border rounded-lg focus:ring-2 focus:ring-indigo-500">
                        </div>

                        <!-- User Personal Info -->
                        <div class="flex flex-col">
                            <label for="first_name" class="text-sm font-medium text-gray-700">First Name:</label>
                            <input type="text" id="first_name" name="first_name" required class="px-4 py-2 mt-2 border rounded-lg focus:ring-2 focus:ring-indigo-500">
                        </div>

                        <div class="flex flex-col">
                            <label for="last_name" class="text-sm font-medium text-gray-700">Last Name:</label>
                            <input type="text" id="last_name" name="last_name" required class="px-4 py-2 mt-2 border rounded-lg focus:ring-2 focus:ring-indigo-500">
                        </div>

                        <div class="flex flex-col">
                            <label for="thana" class="text-sm font-medium text-gray-700">Thana:</label>
                            <input type="text" id="thana" name="thana" required class="px-4 py-2 mt-2 border rounded-lg focus:ring-2 focus:ring-indigo-500">
                        </div>
                        <div class="flex flex-col">
                            <label for="union" class="text-sm font-medium text-gray-700">Union:</label>
                            <input type="text" id="union" name="union" required class="px-4 py-2 mt-2 border rounded-lg focus:ring-2 focus:ring-indigo-500">
                        </div>
                        <div class="flex flex-col">
                            <label for="village" class="text-sm font-medium text-gray-700">Village:</label>
                            <input type="text" id="village" name="village" required class="px-4 py-2 mt-2 border rounded-lg focus:ring-2 focus:ring-indigo-500">
                        </div>
                        <div class="flex flex-col">
                            <label for="zilla" class="text-sm font-medium text-gray-700">Zilla:</label>
                            <input type="text" id="zilla" name="zilla" required class="px-4 py-2 mt-2 border rounded-lg focus:ring-2 focus:ring-indigo-500">
                        </div>

                        <div class="flex flex-col">
                            <label for="nid" class="text-sm font-medium text-gray-700">NID:</label>
                            <input type="text" id="nid" name="nid" class="px-4 py-2 mt-2 border rounded-lg focus:ring-2 focus:ring-indigo-500">
                        </div>

                        <div class="flex flex-col">
                            <label for="date_of_birth" class="text-sm font-medium text-gray-700">Date of Birth:</label>
                            <input type="date" id="date_of_birth" name="date_of_birth" class="px-4 py-2 mt-2 border rounded-lg focus:ring-2 focus:ring-indigo-500">
                        </div>

                        <div class="flex flex-col">
                            <label for="gender" class="text-sm font-medium text-gray-700">Gender:</label>
                            <select id="gender" name="gender" class="px-4 py-2 mt-2 border rounded-lg focus:ring-2 focus:ring-indigo-500">
                                <option value="male">Male</option>
                                <option value="female">Female</option>
                                <option value="other">Other</option>
                            </select>
                        </div>

                        <div class="flex flex-col">
                            <label for="tin" class="text-sm font-medium text-gray-700">TIN:</label>
                            <input type="text" id="tin" name="tin" class="px-4 py-2 mt-2 border rounded-lg focus:ring-2 focus:ring-indigo-500">
                        </div>

                        <div class="flex flex-col">
                            <label for="profile_image" class="text-sm font-medium text-gray-700">Profile Image:</label>
                            <input type="file" id="profile_image" name="profile_image" class="px-4 py-2 mt-2 border rounded-lg">
                        </div>

                        <div class="flex flex-col">
                            <label for="nid_front" class="text-sm font-medium text-gray-700">NID Front Image:</label>
                            <input type="file" id="nid_front" name="nid_front" class="px-4 py-2 mt-2 border rounded-lg">
                        </div>

                        <div class="flex flex-col">
                            <label for="nid_back" class="text-sm font-medium text-gray-700">NID Back Image:</label>
                            <input type="file" id="nid_back" name="nid_back" class="px-4 py-2 mt-2 border rounded-lg">
                        </div>

                        <!-- User Financial Info -->
                        <div class="flex flex-col">
                            <label for="bank_name" class="text-sm font-medium text-gray-700">Bank Name:</label>
                            <input type="text" id="bank_name" name="bank_name" class="px-4 py-2 mt-2 border rounded-lg focus:ring-2 focus:ring-indigo-500">
                        </div>

                        <div class="flex flex-col">
                            <label for="branch_name" class="text-sm font-medium text-gray-700">Branch Name:</label>
                            <input type="text" id="branch_name" name="branch_name" class="px-4 py-2 mt-2 border rounded-lg focus:ring-2 focus:ring-indigo-500">
                        </div>

                        <div class="flex flex-col">
                            <label for="account_name" class="text-sm font-medium text-gray-700">Account Name:</label>
                            <input type="text" id="account_name" name="account_name" class="px-4 py-2 mt-2 border rounded-lg focus:ring-2 focus:ring-indigo-500">
                        </div>

                        <div class="flex flex-col">
                            <label for="account_number" class="text-sm font-medium text-gray-700">Account Number:</label>
                            <input type="text" id="account_number" name="account_number" class="px-4 py-2 mt-2 border rounded-lg focus:ring-2 focus:ring-indigo-500">
                        </div>

                        <!-- User Nominee Info -->
                        <div class="flex flex-col">
                            <label for="nominee_name" class="text-sm font-medium text-gray-700">Nominee Name:</label>
                            <input type="text" id="nominee_name" name="nominee_name" class="px-4 py-2 mt-2 border rounded-lg focus:ring-2 focus:ring-indigo-500">
                        </div>

                        <div class="flex flex-col">
                            <label for="nominee_phone" class="text-sm font-medium text-gray-700">Nominee Phone:</label>
                            <input type="text" id="nominee_phone" name="nominee_phone" class="px-4 py-2 mt-2 border rounded-lg focus:ring-2 focus:ring-indigo-500">
                        </div>

                        <div class="flex flex-col">
                            <label for="nominee_email" class="text-sm font-medium text-gray-700">Nominee Email:</label>
                            <input type="email" id="nominee_email" name="nominee_email" class="px-4 py-2 mt-2 border rounded-lg focus:ring-2 focus:ring-indigo-500">
                        </div>

                        <div class="flex flex-col">
                            <label for="nominee_nid" class="text-sm font-medium text-gray-700">Nominee NID:</label>
                            <input type="text" id="nominee_nid" name="nominee_nid" class="px-4 py-2 mt-2 border rounded-lg focus:ring-2 focus:ring-indigo-500">
                        </div>
                        <button type="submit" class="w-full py-2 px-4 bg-black text-white rounded-lg hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 mt-4">Create User</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/pages/enterprise/user/user_list.html
{% extends '_base.html' %}
{% load static %}
{% block title %}User List{% endblock %}

{% block content %}
    <div class="tp-main-wrapper bg-slate-100 h-screen" x-data="{ sideMenu: false }">

        {% include 'pages/base/sidebar.html' %}

        <div class="tp-main-content lg:ml-[250px] xl:ml-[300px] w-[calc(100% - 300px)]" x-data="{ searchOverlay: false }">

            {% include 'pages/base/header.html' %}

            <div class="body-content px-8 py-8 bg-slate-100">
                <div class="flex justify-between items-center mb-6">
                    <h2 class="text-2xl font-semibold text-gray-800">User List</h2>
                    <div class="flex items-center justify-end gap-4 text-2xl">

{#                    <a href="{% url 'enterprise_service:c' %}" class="tp-btn bg-theme text-white px-6 py-2 rounded-lg hover:bg-theme-dark transition-all">Create New User</a>#}
{#                    <a href="{% url 'administrator_service:create_insurecow_users' %}" class="tp-btn bg-theme text-white px-6 py-2 rounded-lg hover:bg-theme-dark transition-all">Create Insurecow Agent</a>#}
                    </div>

                </div>

                <div class="overflow-x-auto shadow rounded-lg bg-white">
                    <table class="w-full table-auto border-collapse">
                        <thead class="bg-gray-200">
                            <tr>
                                <th class="py-3 px-4 text-left text-sm font-semibold text-gray-600">#</th>
                                <th class="py-3 px-4 text-left text-sm font-semibold text-gray-600">Mobile Number</th>
                                <th class="py-3 px-4 text-left text-sm font-semibold text-gray-600">Role</th>
                                <th class="py-3 px-4 text-left text-sm font-semibold text-gray-600">Status</th>
                                <th class="py-3 px-4 text-left text-sm font-semibold text-gray-600">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for user in user %}
                                <tr class="hover:bg-gray-50 border-b">
                                <td class="py-3 px-4 text-sm text-gray-700">{{ forloop.counter }}</td>
                                    <td class="py-3 px-4 text-sm text-gray-700">{{ user.mobile_number }}</td>
                                    <td class="py-3 px-4 text-sm text-gray-700">{{ user.role.name }}</td>
                                    <td class="py-3 px-4 text-sm">
                                        {% if user.is_active %}
                                            <span class="inline-block py-1 px-3 rounded-full text-sm bg-green-500 text-black">Active</span>
                                        {% else %}
                                            <span class="inline-block py-1 px-3 rounded-full text-sm bg-red-500 text-black">Inactive</span>
                                        {% endif %}
                                    </td>
                                    <td class="py-3 px-4 text-sm">
                                        <a href="#" class="text-blue-500 hover:text-blue-700">Edit</a> |
                                        <a href="#" class="text-red-500 hover:text-red-700">Delete</a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}