administratorservice/urls.py
from django.urls import path

from .views import *

app_name = 'administrator_service'
urlpatterns = [
    path('dashboard/', dashboard, name='dashboard'),
    path('otp/', otp_list, name='otp_list'),
    path('roles/', roles_list, name='roles_list'),
    path('roles/create/', create_roles, name='create_roles'),
    # path('roles/modify/<int:pk>/', update_roles, name='update_roles'),
    # path('roles/modify/<int:pk>/', delete_roles, name='delete_roles'),

    path('asset-type/', asset_type_list, name='asset_type_list'),
    path('asset-type/create/', create_asset_type, name='create_asset_type'),




    path('breed/', breed_list, name='breed_list'),
    path('breed/create/', create_breed, name='create_breed'),

    path('color/', color_list, name='color_list'),
    path('color/create/', create_color, name='create_color'),

    path('vaccination-status/', vaccination_status_list, name='vaccination_status_list'),
    path('vaccination-status/create/', create_vaccination_status, name='create_vaccination_status'),

    path('deworming-status/', deworming_status_list, name='deworming_status_list'),
    path('deworming-status/create/', create_deworming_status, name='create_deworming_status'),

    path('user-module-access/', user_module_access_list, name='user_module_access_list'),
    path('user-module-access/create/', create_user_module_access, name='create_user_module_access'),


    path('users/', users_list, name='users_list'),
    path('users/create/', create_user, name='create_users'),
    path('users/create-insurecow-agent/', create_insurecow_agent, name='create_insurecow_users'),
    # path('users/modify/<int:pk>/', users_roles, name='update_roles'),
    # path('users/modify/<int:pk>/', users_roles, name='delete_roles'),

]

apiservice/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('auth/public/register/step1/', RegisterStep1.as_view(), name='register-step1'),
    path('auth/public/register/verify-otp/', VerifyOTP.as_view(), name='verify-otp'),
    path('auth/public/register/set-password/', SetPassword.as_view(), name='set-password'),

    path('auth/public/forgot-password/request/', ForgotPasswordRequestView.as_view(), name='forgot-password-request'),
    path('auth/public/forgot-password/verify/', ForgotPasswordVerifyOTPView.as_view(), name='forgot-password-verify'),
    path('auth/public/forgot-password/set/', ForgotPasswordSetView.as_view(), name='forgot-password-set'),


    path('auth/public/login/', Login.as_view(), name='login'),

    path('auth/user/personal-info/', SetPersonalInfo.as_view(), name='personal-info'),
    path('auth/user/financial-info/', SetFinancialInfo.as_view(), name='financial-info'),
    path('auth/user/nominee-info/', SetNomineeInfo.as_view(), name='nominee-info'),
    path('auth/user/organization-info/', SetOrganizationInfo.as_view(), name='organization-info'),

    path('auth/public/token/verify/', VerifyTokenView.as_view(), name='verify-token'),

    path('auth/public/role-list/', RoleListAPIView.as_view(), name='role-list'),
    path('auth/admin/role/', RoleListCreateAPIView.as_view(), name='role-list-create'),
    path('auth/admin/role/<int:pk>/', RoleRetrieveUpdateDestroyAPIView.as_view(), name='role-detail'),
    path('auth/user/sub-users/', SubUsersAPIView.as_view(), name='sub-users'),
    path('auth/user/change-password/', ChangePasswordAPIView.as_view(), name='change-password'),

    path('assets-type/', AssetTypeListAPIView.as_view(), name='asset-type-list'),
    path('breeds/', BreedListAPIView.as_view(), name='breed-list'),
    path('colors/', ColorListAPIView.as_view(), name='color-list'),
    path('vaccination-status/', VaccinationStatusListAPIView.as_view(), name='vaccination-status-list'),
    path('deworming-status/', DewormingStatusListAPIView.as_view(), name='deworming-status-list'),

    path('asset-list/', AssetListAPIView.as_view(), name='asset-list'),
    path('create-asset/', AssetCreateAPIView.as_view(), name='asset-create'),
    path('assets/<int:pk>/', AssetDetailAPIView.as_view(), name='asset-detail'),
    path('get-cow/', get_cow_by_reference, name='get_cow_by_reference'),
    path('insurance-product/', CompanyWiseInsuranceAPIView.as_view(), name='nominee-info'),
    path('insurance-apply/', AssetInsuranceCreateAPIView.as_view(), name='asset-insurance-apply'),
    path('insurance-claim/', InsuranceClaimCreateAPIView.as_view(), name='insurance-claim'),
    path('insurance-list/', InsurancelistAPIView.as_view(), name='insurance-claim'),

    path('payments/create/', PaymentInformationCreateView, name='payment-create'),
    path('payments/<int:pk>/', PaymentInformationDetailView.as_view(), name='payment-detail'),

    path('payments/by-insurance/<str:insurance_id>/', PaymentByInsuranceAPIView.as_view(), name='payments-by-insurance'),

]

insuranceportal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('administrator/', include('administratorservice.urls')),
    path('insurecow-agent/', include('insurecowagentservice.urls')),
    path('insurance-company/', include('insurancecompanyservice.urls')),
    path('enterprise/', include('enterpriseservice.urls')),
    path('auth/', include('authservice.urls')),
    path('insurance/', include('insuranceservice.urls')),
    path('', include('coreservice.urls')),
    path('api/v1/', include('apiservice.urls')),
    path('api/lms/', include('livestock_management_system.urls')),
    path('api/gls/', include('general_accounting_management_system.urls')),  
    path('api/ims/', include('insurance_management_system.urls')), 
    path('api/fms/', include('farm_management_system.urls')),   
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT})
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/pages/administrator/user_module_access/create_user_module_access.html
{% extends '_base.html' %}
{% load static %}

{% block title %}
    Create User Module Access
{% endblock title %}

{% block content %}
<div class="body-content px-6 py-8 bg-slate-100">
    <div class="max-w-2xl mx-auto bg-white p-6 rounded-lg shadow-lg">
        <h1 class="text-3xl font-semibold text-gray-800 mb-6 text-center">Create User Module Access</h1>

        <form method="POST" enctype="{% url 'administrator_service:create_user_module_access' %}">
            {% csrf_token %}
            <!-- User Selection -->
            <div class="flex flex-col">
                <label for="user" class="text-sm font-medium text-gray-700">User:</label>
                <select id="user" name="user" required class="px-4 py-2 mt-2 border rounded-lg focus:ring-2 focus:ring-indigo-500">
                    {% for user in user %}
                    <option value="{{ user.id }}">{{ user.mobile_number }}</option>
                    {% endfor %}
                </select>
            </div>
            <!-- Module Selection -->
            <div class="flex flex-col">
                <label for="module" class="text-sm font-medium text-gray-700">Module:</label>
                <select id="module" name="module" required class="px-4 py-2 mt-2 border rounded-lg focus:ring-2 focus:ring-indigo-500">
                  
                    <option value="FARM">FARM</option>
                    <option value="INSURANCE">INSURANCE</option>
                </select>
            </div> 
            <br/>           
            <button type="submit" class="w-full bg-black text-white py-3 rounded-md hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 transition duration-200">Create Module Permission</button>
        </form>

        <div class="mt-4 text-center">
            <a href="{% url 'administrator_service:user_module_access_list' %}" class="text-blue-500 hover:text-blue-600 text-sm">Back to User Module Access List</a>
        </div>
    </div>
</div>

{% endblock content %}

templates/pages/administrator/user_module_access/user_module_access_list.html
{% extends '_base.html' %}
{% load static %}
{% block title %}User Module Access List{% endblock %}

{% block content %}
            <div class="body-content px-8 py-8 bg-slate-100">
                <div class="flex justify-between items-center mb-6">
                    <h2 class="text-2xl font-semibold text-gray-800">User Module Access List</h2>
                    <a href="{% url 'administrator_service:create_user_module_access' %}" class="tp-btn bg-theme text-white px-6 py-2 rounded-lg hover:bg-theme-dark transition-all">Create New User Module Access</a>
                </div>

                <div class="overflow-x-auto shadow rounded-lg bg-white">
                    <table class="w-full table-auto border-collapse">
                        <thead class="bg-gray-200">
                            <tr>
                                <th class="py-3 px-4 text-left text-sm font-semibold text-gray-600">#</th>
                                <th class="py-3 px-4 text-left text-sm font-semibold text-gray-600">User</th>
                                <th class="py-3 px-4 text-left text-sm font-semibold text-gray-600">Module</th>
                                <th class="py-3 px-4 text-left text-sm font-semibold text-gray-600">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for access in user_module_access_list %}
                                <tr class="hover:bg-gray-50 border-b">
                                    <td class="py-3 px-4 text-sm text-gray-700">{{ forloop.counter }}</td>
                                    <td class="py-3 px-4 text-sm text-gray-700">{{ access.user_name }} | {{ access.mobile_number }}</td>
                                    <td class="py-3 px-4 text-sm text-gray-700">{{ access.module_code }}</td>
                                    <td class="py-3 px-4 text-sm">
                                        <a href="#" class="text-blue-500 hover:text-blue-700">Edit</a> |
                                        <a href="#" class="text-red-500 hover:text-red-700">Delete</a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

{% endblock content %}